#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

echo "🧪 Compilando el proyecto con dotnet build..."

dotnet build --configuration Release

if [ $? -ne 0 ]; then
  echo "❌ Falló la compilación. No se permite el push."
  exit 1
fi

echo "✅ Compilación exitosa. Procediendo con el push."
