#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

echo "🔍 Ejecutando validación de formato (dotnet format)..."
dotnet format Taller.csproj --verify-no-changes

if [ $? -ne 0 ]; then
  echo "❌ El código no está formateado correctamente. Ejecuta 'dotnet format' para corregirlo."
  exit 1
fi

echo "✅ Formato correcto."
